### ISSUE TITLE
Run.conf: ipv4_addr or ipaddr 

### ISSUE THREAD

**Issue by MalloZup** [okirch/susetest#12]
## Issue with run.conf

Calling  `client.ipaddr` from run, the method return string None.

but when i call `client.run or client.name` method command is executed and for `client.name` i get the right string.

Calling  this method inside the  SLEnkins framework,   it return  the right ip-adress of the machine.
So i cannot figure out why, precisely works with SLEnkins and not without. 

Probably i'm missing something, but i'm interested to know how the run.conf work in deep.
### config or run.conf  that has the issue with the parser

```
workspace "/tmp/worky";
node "client" {
      target       "ssh:192.168.15.139";
      ipaddr       "192.168.15.139";
}
```

**Comment by MalloZup** [comment]
### Between documentation HOWTO and twopence-example , we have following diff

ipv4_addr vs ipaddr 

```
 workspace "/tmp/twopence-rpc";
  node "server" {
      target       "ssh:192.168.10.1";
      ipaddr       "192.168.10.1";
  }
  node "client" {
      target       "ssh:192.168.10.2";
      ipaddr       "192.168.10.2";
  }
```

```
node "client" {
    target       "ssh:127.0.0.1";
    ipv4_addr    "127.0.0.1";
}
```

With this configuration everything works fine. 

The problem subsist on the parser side.

We have 2 names for the same variables, imho. (maybe i'm not correct)

```
 self.ipaddr = self.ipv4_addr
 self.ip6addr = self.ipv6_addr

```

**Comment by MalloZup** [comment]
**susetest/python/config.c.**

```
static PyObject *
Config_node_internal_ip(susetest_Config *self, PyObject *args, PyObject *kwds)
{
    return __firstlevel_string_attr(self, args, kwds, "node", "ipv4_addr");
}
```

Imho i don't know if there is a difference  ipv4_addr  and ipaddr. 

If  there is no difference, i will update the HOWTO documentation, to use only ipv4_addr/ipv6_addr

```
node "client" {
    target       "ssh:127.0.0.1";
    ipv4_addr    "127.0.0.1";
}
```

**Comment by okirch** [comment]
Hi Dario,

On Sat, 2016-04-30 at 07:04 -0700, Dario Maiocchi wrote:

> Hi Olaf,
> currently i'm researching how to use susetest on bare machines &&
> running it without any dependencies from testing frameworks. 
> With this use-case, perspective, i see only advantages, because the
> tests could be used everywhere, without taking care of the work of
> testing-framework/integration. (SLEnkins, OpenQA, docker-container,
> bare-machines, etc.) and now i think i understand why, you choose the
> generic name "susetest" and why this embrace precisely my idea of
> testing too. This is a lot of freedom and advantages together ! :) . I
> think i get only now the whole picture of susetest :+1:

:-)

> I have already experimented running susetest on two vms created with
> the prerequisites, and it works nice. 
> 
> The only on issue for moment that i have, is that i get a "None" type
> when calling 
> 
> I call this method on SLEnkins, and it give me the right ip-adress of the machine.
>  So i cannot figure out why, precisely works with SLEnkins and not without. 
> 
> looking at the susetest.py i found one comment:
>     # XXXX: Currently broken
>     if_ipaddr = interface.get('ipv4_addr')
>     if not if_ipaddr:
>         print "%s: no ipv4 addr for interface %s" % (self.name, interface.name)
>         return None
> So my question is the comment is now outdated, or the issue persist already, or probably i'm missing something.

I think the main reason is that at some point, Eric and I agree that
that config file would provide the node's address in the "ipaddr"
attribute. Then, as Eric introuced ipv6 support in his slenkins scripts,
he wanted to clean things up and use ipv4_addr and ipv6_addr. So his
scripts now generate config files that set ipv4_addr; and maybe the also
set ipaddr for backward compatibility.

It's quite possible that susetest still contains some stuff for
backwards compatibility - I don't really recall.

Probably the best approach is to ensure that all tools (and all
documentation :-) agree on the name of the parameter - which should
probably be ipv4_addr. But please check with Eric whether he intends to
change that at some point in the future.

Once the tools and the documentation agree, I would go through all
susetest code to make sure it no longer refers to "ipaddr".

Hope this helps,
Olaf

> ###config or run.conf "file"
> 
> workspace "/tmp/worky";
> node "client" {
> target "ssh:192.168.15.139";
> ipaddr "192.168.15.139";
> }
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

## 

Olaf Kirch - Director SUSE Linux Enterprise; R&D (okir@suse.com)
SUSE Linux GmbH, Maxfeldstr. 5, 90409 Nürnberg, Germany
GF: Felix Imendörffer, Jane Smithard, Dilip Upmanyu, Graham Norton,
HRB 21284 (AG Nürnberg)

**Comment by MalloZup** [comment]
Hi Olaf,
ipaddr -> ipv4_addr changed on HOWTO.doc. :)

**Comment by MalloZup** [comment]
i close the issue, since the howto is update. :)
